// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK7NOMR7PcZlVJ-jpREuefAJCZ-zXlJbQ',
    appId: '1:322837220339:web:b23eea4ba085d18b672086',
    messagingSenderId: '322837220339',
    projectId: 'pelatihanmobile',
    authDomain: 'pelatihanmobile.firebaseapp.com',
    storageBucket: 'pelatihanmobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg-yKc5nttIfvZdmdntYizGZyapC8LYnc',
    appId: '1:322837220339:android:105d42cec869e6c1672086',
    messagingSenderId: '322837220339',
    projectId: 'pelatihanmobile',
    storageBucket: 'pelatihanmobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoUxNQiopTcRvhBeSq0DMDFXB26L-PsQQ',
    appId: '1:322837220339:ios:836b62e72a5c9cfc672086',
    messagingSenderId: '322837220339',
    projectId: 'pelatihanmobile',
    storageBucket: 'pelatihanmobile.firebasestorage.app',
    iosBundleId: 'com.example.appjumat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoUxNQiopTcRvhBeSq0DMDFXB26L-PsQQ',
    appId: '1:322837220339:ios:836b62e72a5c9cfc672086',
    messagingSenderId: '322837220339',
    projectId: 'pelatihanmobile',
    storageBucket: 'pelatihanmobile.firebasestorage.app',
    iosBundleId: 'com.example.appjumat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK7NOMR7PcZlVJ-jpREuefAJCZ-zXlJbQ',
    appId: '1:322837220339:web:026d693ccc0fbaf0672086',
    messagingSenderId: '322837220339',
    projectId: 'pelatihanmobile',
    authDomain: 'pelatihanmobile.firebaseapp.com',
    storageBucket: 'pelatihanmobile.firebasestorage.app',
  );
}
